services:
  - type: web
    name: techtak-api
    env: node
    root: Back
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FRONTEND_ORIGIN
        value: https://seu-site-netlify.netlify.app
